### ISSUE TITLE
Zone IDs not supported

### ISSUE THREAD

**Issue by jtdaugherty** [MichelBoucey/IPv6Addr#3]
I'd like to parse IPv6 addresses with zone IDs as describe at

https://4sysops.com/archives/ipv6-tutorial-part-7-zone-id-and-unique-local-ipv6-unicast-addresses/

but right this library won't parse such addresses.

**Comment by MichelBoucey** [comment]
No, it won't. You are right.

It is not supported yet, and if you refer to <a href="https://tools.ietf.org/html/rfc6874">RFC6874</a>, it seems to me that such syntax is not yet enough mature and well-defined to be properly and easily parsed (Cf. Section 2, Specification).

**Comment by jtdaugherty** [comment]
Okay; fair enough. Thanks!
